-- SQL Query to insert accommodations for Booking reference 'TT00928'

-- 1. Insert Accommodation: Al Shohda Hotel
INSERT INTO "AccommodationService" (
  "id", 
  "bookingId", 
  "vendorId", 
  "hotelName", 
  "roomType", 
  "checkInDate", 
  "checkOutDate", 
  "mealType", 
  "reservationNumber", 
  "qty", 
  "price", 
  "currency", 
  "otherCurrency", 
  "conversionRate", 
  "issueDate", 
  "refundAmount", 
  "fineAmount", 
  "hotelConfirmationNumber", 
  "hotelAddress", 
  "lastCancellationDate"
) VALUES (
  '43376183-81ba-4c1c-a5e1-b3472b057e84', 
  (SELECT id FROM "Booking" WHERE "bookingReference" = 'TT00928'), 
  (SELECT id FROM "Vendor" WHERE LOWER(name) = 'emaar group' LIMIT 1), 
  'Al Shohda Hotel', 
  'Quad Room', 
  '2026-07-29 23:00:00', 
  '2026-08-04 23:00:00', 
  'Breakfast', 
  'URB/R/6/2026/21194', 
  2, 
  0, 
  'GBP', 
  NULL, 
  NULL, 
  NULL, 
  0, 
  0, 
  NULL, 
  NULL, 
  NULL
) ON CONFLICT ("id") DO NOTHING;

-- 2. Insert Accommodation: Shaza Regency Plaza Madinah
INSERT INTO "AccommodationService" (
  "id", 
  "bookingId", 
  "vendorId", 
  "hotelName", 
  "roomType", 
  "checkInDate", 
  "checkOutDate", 
  "mealType", 
  "reservationNumber", 
  "qty", 
  "price", 
  "currency", 
  "otherCurrency", 
  "conversionRate", 
  "issueDate", 
  "refundAmount", 
  "fineAmount", 
  "hotelConfirmationNumber", 
  "hotelAddress", 
  "lastCancellationDate"
) VALUES (
  '4242f10e-6784-4870-b7c1-c69756b311e7', 
  (SELECT id FROM "Booking" WHERE "bookingReference" = 'TT00928'), 
  (SELECT id FROM "Vendor" WHERE LOWER(name) = 'maysan group' LIMIT 1), 
  'Shaza Regency Plaza Madinah', 
  'Quad', 
  '2026-08-04 23:00:00', 
  '2026-08-10 23:00:00', 
  'Breakfast', 
  '450462-1', 
  2, 
  0, 
  'GBP', 
  NULL, 
  NULL, 
  NULL, 
  0, 
  0, 
  NULL, 
  NULL, 
  NULL
) ON CONFLICT ("id") DO NOTHING;
